# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='所属'),
        ),
    ]
